### ISSUE TITLE
Please fix the issue for 2020.3 version

### ISSUE THREAD

**Issue by TheRunningRad1313** [Unity-Technologies/SpaceshipDemo#13]
hi, i want to use the project files in 2020.3 but when i import the files it is showing compilation error.Thank you

**Comment by peeweek** [comment]
Hello! Could you give me more insight on the actual version you are using, and if you can log the error message?
(So far I've been testing it until 2020.3.3f1 so it could break on newer versions)

**Comment by peeweek** [comment]
I've been testing it as well on Windows editor 2020.3.5f1 and it did work.

**Comment by TheRunningRad1313** [comment]
now it is working, thank you
