### ISSUE TITLE
2022.2.6f1 cannot be opened normally

### ISSUE THREAD

**Issue by sajajj** [Unity-Technologies/SpaceshipDemo#20]
An error occurred while resolving packages:Project has invalid dependencies:com,unity.toolchain.win-x86 64-inux-x86 64:Request POSTnttps://api.unity.com/v1/oauth2/authorize] failedwith status code [500] click on Retry to relaunch Unity and reopen yourproject. click on Continue to launch Unity. Some or allpackages may not be imported which may causecompilation errors

**Comment by VitaVFX** [comment]
Hi! Could you please provide steps of reproduction for further investigation (have you cloned the project or downloaded)? On my end it seems to work fine :) 

![Test - Compilation Errors](https://user-images.githubusercontent.com/66080609/234774973-a98846da-820d-4873-84a3-5a32bea334f7.png)
