### ISSUE TITLE
error CS0246: The type or namespace name 'Cinemachine' could not be found

### ISSUE THREAD

**Issue by sasa42** [Unity-Technologies/SpaceshipDemo#3]
Unity 2019.2.0

GIT LFS checkout 
and
Download Release

fire following error after import

LocalPackages\net.peeweek.gameplay-ingredients\Runtime\Managers\Implementations\VirtualCameraManager.cs(4,7): error CS0246: The type or namespace name 'Cinemachine' could not be found (are you missing a using directive or an assembly reference?)

Cinemachine ist installed over PackageManager

**Comment by peeweek** [comment]
That's pretty strange. Often, this kind of error occurs while unity upgrades the `Packages/manifest.json` but this is occuring while opening with a newer, major release of unity. 

I have made some tests with latest changes and still can't repro your issue :(

Could you try the following, just to be sure?
- Close the editor, Delete the library folder, then reimport everything?
- Perform a `git reset --hard` and a `git clean -fdx` command?

If it still doesn't work, could you send me a bit more info about your configuration? (CPU, GPU, OS Version, Unity Version (All text found in `ProjectSettings/ProjectVersion.txt`)

Thank you

**Comment by sasa42** [comment]
Hi,

m_EditorVersion: 2019.2.0f1
m_EditorVersionWithRevision: 2019.2.0f1 (20c1667945cf)

Windows 10  1809
NVidia GTX 1080
Intel I7-6920HQ CPU

I tried on 2x GIT LFS and 2x Download as .zip.
I deleted the library Folder.
I deleted the LocalPackages and reatached them via PackageManager
SpaceshipDemo-Project-2019.2.0\LocalPackages
I tried all Cinemachine version available in PAckageManager.

**Comment by sasa42** [comment]
Editor.log. Sorry. Could not upload the file.

[UnityConnectServicesConfig] "clientHandshakeTimeoutSec" was set to "2" but has been clamped to "10"
[UnityConnectServicesConfig] local config found
[UnityConnectServicesConfig] "servicesConfigBaseUrl" is set to "http://unityhub.bmwgroup.net/config"
[UnityConnectServicesConfig] "disableServicesWindow" is set to "false"
[UnityConnectServicesConfig] "enableEntitlementLicensing" is set to "true"
[UnityConnectServicesConfig] "disableUserLogin" is set to "false"
[UnityConnectServicesConfig] "disableCollabWindow" is set to "false"
[UnityConnectServicesConfig] "entitlementCacheTimeoutInSeconds" is set to "60"
[UnityConnectServicesConfig] "clientConnectTimeoutSec" is set to "1"
[UnityConnectServicesConfig] "clientHandshakeTimeoutSec" is set to "10"
[UnityConnectServicesConfig] "clientResolveEntitlementsTimeoutSec" is set to "1"
[Licensing::Module] Successfully connected to LicensingClient on channel: LicenseClient-Q237091
[LicensingClient] ERROR Error 10 while verifying Licensing Client signature (path: 1180, process Id: C:/Program Files/Unity.Licensing.Client/Unity.Licensing.Client.exe)
[Licensing::Module] LicensingClient has failed validation
[LicensingClient] ERROR Failed to connect to local IPC
[Licensing::Module] Failed to connect to channel: LicenseClient-Q237091-2019.2.0
[Licensing::Module] Successfully launched the LicensingClient
[Licensing::Module] Successfully connected to LicensingClient on channel: LicenseClient-Q237091-2019.2.0
[Licensing::Module] Successfully launched and connected to LicensingClient
Entitlement-based licensing initiated
Built from '2019.2/staging' branch; Version is '2019.2.0f1 (20c1667945cf) revision 2146662'; Using compiler version '191627012'
OS: 'Windows 10  (10.0.0) 64bit' Language: 'de' Physical Memory: 65489 MB
BatchMode: 0, IsHumanControllingUs: 1, StartBugReporterOnCrash: 1, Is64bit: 1, IsPro: 1
[Package Manager] Server::Start -- Port 58665 was selected
Setting up noproxy from UNITY_NOPROXY environment variable. Setting to: localhost,127.0.0.1
Setting up proxyserver from UNITY_PROXYSERVER environment variable. Setting to: http://qqvrst0:pap96and@proxy.muc:8080

 COMMAND LINE ARGUMENTS:
C:\Unity\2019.2.0f1\Editor\Unity.exe
-projectpath
E:/temp/23_02/SpaceshipDemo-Project-2019.2.0
-useHub
-hubIPC
-cloudEnvironment
production
-hubSessionId
d7dabf60-c32e-11e9-ad3c-17f7601a2e55
Successfully changed project path to: E:/temp/23_02/SpaceshipDemo-Project-2019.2.0
E:/temp/23_02/SpaceshipDemo-Project-2019.2.0
Using Asset Import Pipeline V1.
Setting up noproxy from UNITY_NOPROXY environment variable. Setting to: localhost,127.0.0.1
Setting up proxyserver from UNITY_PROXYSERVER environment variable. Setting to: http://qqvrst0:pap96and@proxy.muc:8080
Rebuilding Library because the asset database could not be found!
 
(Filename: C:\buildslave\unity\build\Modules/AssetDatabase/Editor/Shared/AssetDatabaseInitialization.cpp Line: 108)

FMOD failed to initialize. This may be because your sound card is configured to give applications exclusive access, thus preventing Unity from using this device. You can change this in Control Panel > Audio Devices and Sound Themes > Playback Device > Properties > Options ... : "Soundcard does not support the minimum features needed for this soundsystem (16bit stereo output). " (59)
 
(Filename: C:\buildslave\unity\build\Modules/Audio/Public/AudioManager.cpp Line: 1470)

Forced to initialize FMOD to to the device driver's system output rate 48000, this may impact performance and/or give inconsistent experiences compared to selected sample rate 48000
 
(Filename: C:\buildslave\unity\build\Modules/Audio/Public/AudioManager.cpp Line: 1413)

FMOD failed to initialize. This may be because your sound card is configured to give applications exclusive access, thus preventing Unity from using this device. You can change this in Control Panel > Audio Devices and Sound Themes > Playback Device > Properties > Options ... : "Soundcard does not support the minimum features needed for this soundsystem (16bit stereo output). " (59)
 
(Filename: C:\buildslave\unity\build\Modules/Audio/Public/AudioManager.cpp Line: 1470)

FMOD failed to initialize any audio devices, running on emulated software output with no sound. Please check your audio drivers and/or hardware for malfunction.
Loading GUID <-> Path mappings...0.000146 seconds
Loading Asset Database...0.000037 seconds
AssetDatabase consistency checks...0.000249 seconds
Setting up noproxy from UNITY_NOPROXY environment variable. Setting to: localhost,127.0.0.1
Setting up proxyserver from UNITY_PROXYSERVER environment variable. Setting to: http://qqvrst0:pap96and@proxy.muc:8080
[Package Manager] Done resolving packages in 17.30s seconds
[Package Manager] 
The following packages were not registered (reason: failed entitlement check).
  com.unity.cinemachine@2.3.4
  com.unity.ide.rider@1.0.8
  com.unity.ide.visualstudio@1.0.11
  com.unity.ide.vscode@1.0.7
  com.unity.render-pipelines.high-definition@6.9.1-preview
  com.unity.textmeshpro@2.0.1
  com.unity.ext.nunit@1.0.0
  com.unity.render-pipelines.core@6.9.1
  com.unity.shadergraph@6.9.1
  com.unity.visualeffectgraph@6.9.1-preview

[Package Manager] Done checking package constraints in 0.01s seconds
[Package Manager] 
Registered 38 packages:
  Built-in packages:
    com.unity.package-manager-ui@2.2.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.package-manager-ui)
    com.unity.timeline@1.1.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.timeline)
    com.unity.ugui@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.ugui)
    com.unity.modules.ai@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.ai)
    com.unity.modules.androidjni@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.androidjni)
    com.unity.modules.animation@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.animation)
    com.unity.modules.assetbundle@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.assetbundle)
    com.unity.modules.audio@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.audio)
    com.unity.modules.cloth@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.cloth)
    com.unity.modules.director@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.director)
    com.unity.modules.imageconversion@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.imageconversion)
    com.unity.modules.imgui@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.imgui)
    com.unity.modules.jsonserialize@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.jsonserialize)
    com.unity.modules.particlesystem@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.particlesystem)
    com.unity.modules.physics@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.physics)
    com.unity.modules.physics2d@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.physics2d)
    com.unity.modules.screencapture@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.screencapture)
    com.unity.modules.terrain@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.terrain)
    com.unity.modules.terrainphysics@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.terrainphysics)
    com.unity.modules.tilemap@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.tilemap)
    com.unity.modules.ui@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.ui)
    com.unity.modules.uielements@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.uielements)
    com.unity.modules.umbra@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.umbra)
    com.unity.modules.unityanalytics@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.unityanalytics)
    com.unity.modules.unitywebrequest@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.unitywebrequest)
    com.unity.modules.unitywebrequestassetbundle@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.unitywebrequestassetbundle)
    com.unity.modules.unitywebrequestaudio@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.unitywebrequestaudio)
    com.unity.modules.unitywebrequesttexture@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.unitywebrequesttexture)
    com.unity.modules.unitywebrequestwww@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.unitywebrequestwww)
    com.unity.modules.vehicles@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.vehicles)
    com.unity.modules.video@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.video)
    com.unity.modules.vr@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.vr)
    com.unity.modules.wind@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.wind)
    com.unity.modules.xr@1.0.0 (location: C:\Unity\2019.2.0f1\Editor\Data\Resources\PackageManager\BuiltInPackages\com.unity.modules.xr)
  Local packages:
    com.unity.vfx-toolbox@file:E:\temp\23_02\SpaceshipDemo-Project-2019.2.0\LocalPackages\com.unity.vfx-toolbox (location: E:\temp\23_02\SpaceshipDemo-Project-2019.2.0\LocalPackages\com.unity.vfx-toolbox)
    net.peeweek.build-frontend@file:E:\temp\23_02\SpaceshipDemo-Project-2019.2.0\LocalPackages\net.peeweek.build-frontend (location: E:\temp\23_02\SpaceshipDemo-Project-2019.2.0\LocalPackages\net.peeweek.build-frontend)
    net.peeweek.console@file:E:\temp\23_02\SpaceshipDemo-Project-2019.2.0\LocalPackages\net.peeweek.console (location: E:\temp\23_02\SpaceshipDemo-Project-2019.2.0\LocalPackages\net.peeweek.console)
    net.peeweek.gameplay-ingredients@file:E:\temp\23_02\SpaceshipDemo-Project-2019.2.0\LocalPackages\net.peeweek.gameplay-ingredients (location: E:\temp\23_02\SpaceshipDemo-Project-2019.2.0\LocalPackages\net.peeweek.gameplay-ingredients)

[XR] No new subsystems found in resolved package list.
[Package Manager] Done registering packages in 0.01s seconds
Refreshing native plugins compatible for Editor in 0.02 ms, found 0 plugins.
Preloading 0 native plugins for Editor in 0.00 ms.
IsTimeToCheckForNewEditor: Update time 1566303824 current 1566304980
Initialize engine version: 2019.2.0f1 (20c1667945cf)
[XR] Discovering subsystems at path C:/Unity/2019.2.0f1/Editor/Data/Resources/UnitySubsystems
[XR] Discovering subsystems at path E:/temp/23_02/SpaceshipDemo-Project-2019.2.0/Assets
GfxDevice: creating device client; threaded=1
Setting up noproxy from UNITY_NOPROXY environment variable. Setting to: localhost,127.0.0.1
Setting up proxyserver from UNITY_PROXYSERVER environment variable. Setting to: http://qqvrst0:pap96and@proxy.muc:8080
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1080 (ID=0x1ba0)
    Vendor:   
    VRAM:     8079 MB
    Driver:   26.21.14.3136
[EnlightenBakeManager] m_Clear = false;
Initialize mono
Mono path[0] = 'C:/Unity/2019.2.0f1/Editor/Data/Managed'
Mono path[1] = 'C:/Unity/2019.2.0f1/Editor/Data/MonoBleedingEdge/lib/mono/unityjit'
Mono config path = 'C:/Unity/2019.2.0f1/Editor/Data/MonoBleedingEdge/etc'
Using monoOptions --debugger-agent=transport=dt_socket,embedding=1,server=y,suspend=n,address=127.0.0.1:56968
Begin MonoManager ReloadAssembly
Registering precompiled unity dll's ...
Register platform support module: C:/Unity/2019.2.0f1/Editor/Data/PlaybackEngines/WindowsStandaloneSupport/UnityEditor.WindowsStandalone.Extensions.dll
Register platform support module: C:/Unity/2019.2.0f1/Editor/Data/PlaybackEngines/MetroSupport/UnityEditor.UWP.Extensions.dll
Registered in 0.005391 seconds.
Native extension for WindowsStandalone target not found
Refreshing native plugins compatible for Editor in 0.00 ms, found 0 plugins.
Preloading 0 native plugins for Editor in 0.00 ms.
Mono: successfully reloaded assembly
- Completed reload, in  3.740 seconds
Registering precompiled user dll's ...
Registered in 0.065048 seconds.
Platform modules already initialized, skipping
Begin MonoManager ReloadAssembly
Native extension for WindowsStandalone target not found
Refreshing native plugins compatible for Editor in 0.00 ms, found 0 plugins.
Preloading 0 native plugins for Editor in 0.00 ms.
Mono: successfully reloaded assembly
- Completed reload, in  0.534 seconds
Platform modules already initialized, skipping
[ScriptCompilation] Recompiling all scripts because: Reload of assemblies failed, assemblies are invalid or forced recompiled
Validating Project structure ... 0.016738 seconds.
Shader import version has changed; will reimport all shaders...
Upgrading shader files ...0.032043 seconds.
Refresh: detecting if any assets need to be imported or removed ...
Removing Packages/com.unity.vfx-toolbox/ImageSequencer/Editor/Public because the asset does not exist
 
(Filename: C:\buildslave\unity\build\Modules/AssetDatabase/Editor/V1/AssetInterface.cpp Line: 998)

**Comment by sasa42** [comment]
Hello,

the problem is solved.
We have a package manager mirror behind company our firewall and proxy.
Strang things happen.
The packages where all there before.
But by using an standard internet connection they get udownloaded and updated again and it works.

**Comment by peeweek** [comment]
Oh, glad you were able to solve it! Enjoy discovering the demo :)
