### ISSUE TITLE
The meshes does not show in either the editor window or in play mode.

### ISSUE THREAD

**Issue by cubrman** [Unity-Technologies/SpaceshipDemo#4]
Hey,

I’ve launched the editor exactly as suggested in the description, but I have this error running all the time and I can’t see anything but vfx cubes:

http://i.piccy.info/i9/f18dd3f54ee396e7d908a2efa59c696a/1566573415/51302/1315075/1.jpg

http://i.piccy.info/i9/f54c4076847c8f6f59e43c6b4f78b65f/1566573481/87343/1315075/2.jpg

aaand there is no sound.

I tried launching the level both from the “Discover” window and from loading the “Main menu” scene and playing it to choose “Start” - same issue.

**Comment by brnkhy** [comment]
@cubrman this is most likely because your git client doesn't have LFS and it wasn't able to pull big files like meshes, sounds etc.
I would suggest downloading package ,instead of pulling repo, which will guaranteed to have everything. If that works, you'll know it's indeed the LFS problem.

**Comment by cubrman** [comment]
No, I never used Git client - I simply downloaded Zip. Currently unzipped project weighs 650 mb.

**Comment by brnkhy** [comment]
@cubrman that's interesting. My unzipped project folder is around 3.3gb so maybe, some other way, you're missing those files.

**Comment by cubrman** [comment]
I am downloading the GIT project right now - it's only 192 mb, what am I doing wrong?

**Comment by cubrman** [comment]
SpaceshipDemo->Clone or Download->Download Zip

**Comment by brnkhy** [comment]
@cubrman if you follow the `Here` link in this page so should get a 1.7gb zip file, containing everything you need; https://github.com/Unity-Technologies/SpaceshipDemo/releases

**Comment by cubrman** [comment]
Thanks!

**Comment by kwea123** [comment]
the "HERE" link is missing in the latest release (2019.3.3)
